spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/what-to-eat?retryWrites=true&w=majority
#mongodb://mongodb0.example.com:27017
app:
  auth:
    tokenSecret: 926D96C90030DD58429D2751AC1BDBBC
    tokenExpirationMsec: 864000000
  oauth2:
    # After successfully authenticating with the OAuth2 Provider,
    # we'll be generating an auth token for the user and sending the token to the
    # redirectUri mentioned by the frontend client in the /oauth2/authorize request.
    # We're not using cookies because they won't work well in mobile clients.

